# Generated by Django 4.2.1 on 2023-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_card_deck_alter_deck_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
